---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: {{ .Values.app.image }}:{{ default .Chart.AppVersion .Values.app.tag }}
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          ports:
            - containerPort: {{ .Values.app.containerPort }}
              protocol: TCP
          env:
            - name: DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  key: datasource_url
                  name: secret-config
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: datasource_username
                  name: secret-config
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: datasource_password
                  name: secret-config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 50%