---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: myapp-service
spec:
  ports:
    - port: {{ .Values.app.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.app.containerPort }}
  selector:
    app: myapp
  type: ClusterIP